title: Sebeblije
tagline: Budi sebebom!
email: sebeblije@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sebeblije je stranica koja promoviše izvorno učenje vjere islam prema Časnom Kur'anu i Sunnetu Poslanika Muhammeda s.a.v.s.
facebook_path: https://www.facebook.com/sebeblije
twitter_path: https://www.twitter.com/sebeblije
youtube_path: https://www.youtube.com/channel/UCtiz33KO2l_8gqrc0QPIWUw

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass

# PRIČE I KAZIVANJA
collections:
  price:
    output: true
